services:
  - type: web
    name: auto-upload-pipeline
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SHEET_ID
        value: 1NDsmxhPQEnA8Dh-JRmITQt7yFlFuLlOY9Ql_uktpMCk
      - key: SHEET_RANGE
        value: Trang tính1
      - key: DRIVE_FOLDER_ID
        value: 1i2JYb6XElc24y1DWgT9Pu90t1A8qhjXq
      - key: PRIVACY_STATUS
        value: public 
      - key: CATEGORY_ID
        value: "24"
      - key: FB_GRAPH_VERSION
        value: v25.0
      - key: AUTH_KEY
        value: biann2024
      - key: FB_PAGE_ID
        sync: false
      - key: FB_ACCESS_TOKEN
        sync: false
      - key: CLIENT_SECRET_JSON
        sync: false
      - key: TOKEN_JSON
        sync: false
